AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploy four Lambda functions with S3 bucket created by stack

Parameters:
  SearchFunctionS3Key:
    Type: String
    Description: S3 key for Search_Function.zip
  SearchGatewayS3Key:
    Type: String
    Description: S3 key for Search_Gateway.zip
  UploadToSearchS3Key:
    Type: String
    Description: S3 key for Upload_to_search.zip
  PdfToTxtS3Key:
    Type: String
    Description: S3 key for pdftotxt.zip

Resources:
  LambdaArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  SearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SearchFunction
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri:
        Bucket: !Ref LambdaArtifactsBucket
        Key: !Ref SearchFunctionS3Key
      MemorySize: 128
      Timeout: 30
      Policies: AWSLambdaBasicExecutionRole

  SearchGateway:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SearchGateway
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri:
        Bucket: !Ref LambdaArtifactsBucket
        Key: !Ref SearchGatewayS3Key
      MemorySize: 128
      Timeout: 30
      Policies: AWSLambdaBasicExecutionRole

  UploadToSearch:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: UploadToSearch
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri:
        Bucket: !Ref LambdaArtifactsBucket
        Key: !Ref UploadToSearchS3Key
      MemorySize: 128
      Timeout: 30
      Policies: AWSLambdaBasicExecutionRole

  PdfToTxt:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PdfToTxt
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri:
        Bucket: !Ref LambdaArtifactsBucket
        Key: !Ref PdfToTxtS3Key
      MemorySize: 128
      Timeout: 30
      Policies: AWSLambdaBasicExecutionRole

Outputs:
  LambdaArtifactsBucketName:
    Description: Name of the S3 bucket for Lambda artifacts
    Value: !Ref LambdaArtifactsBucket
  SearchFunctionArn:
    Description: ARN of the SearchFunction Lambda
    Value: !GetAtt SearchFunction.Arn
  SearchGatewayArn:
    Description: ARN of the SearchGateway Lambda
    Value: !GetAtt SearchGateway.Arn
  UploadToSearchArn:
    Description: ARN of the UploadToSearch Lambda
    Value: !GetAtt UploadToSearch.Arn
  PdfToTxtArn:
    Description: ARN of the PdfToTxt Lambda
    Value: !GetAtt PdfToTxt.Arn